added newPython file
CodyNicholson/Song_Lyric_Rhyme_Analysis_Project pull request #2
Opened 2020-10-22 23:57 UTC by TheoKhayat

2020-10-22 23:59 UTC, neefasa reviewed
Should print hi cody and nick!!

2020-10-23 00:06 UTC, CodyNicholson requested changes
I agree with nick!

2020-10-23 00:18 UTC, CodyNicholson approved these changes

2020-10-23 00:18 UTC, neefasa approved these changes
Sure it's fine

2020-10-23 00:18 UTC, merged